### ISSUE TITLE
Release in tar.gz ?

### ISSUE THREAD

**Issue by WTFKr0** [msoap/shell2http#20]
Hi !
Is there a way to have a tar.gz release ?
I plan to add your binary like that in my Dockerfile : 
ADD https://github.com/msoap/shell2http/releases/download/1.7/shell2http-1.7.linux.amd64.tar.gz /
But it has to be a direct link or a tar.gz

Thanx for reading

**Comment by msoap** [comment]
Agree, for Linux `.tar.gz` is a more appropriate format.
Done, see latest release: https://github.com/msoap/shell2http/releases/tag/1.8

**Comment by WTFKr0** [comment]
Thanx lot
