### ISSUE TITLE
Reply script with no value

### ISSUE THREAD

**Issue by corrpel** [msoap/shell2http#34]
Hi,
Can this be achieved? Let me tell you what is going on here.
I have a script that stays on the screen after executing, i've tried sending it to >dev/null with success but http still waits for response until a timeout is displayed. What i want to do is access the "/command" and the website to reply with no content.
Thanks.

**Comment by msoap** [comment]
Hi,

What do you mean "stays on the screen"? Please provide minimal example. 

Shell script with no content like this: `shell2http /test 'echo "text" > /dev/null'` - works properly.
