### ISSUE TITLE
-form doesn't seem to work

### ISSUE THREAD

**Issue by silverBull3t** [msoap/shell2http#35]
Hi,
I really like you implementation. this simple yet powerful shell can really help me.
I'm having trouble with the "-form" option.

no matter what i try the $v_xx doesn't work.

shell2http -form /test "echo $v_xx"
running this with the URL "http://localhost:8080/test?xx=123"
the output I get is "$v_xx"

any ideas ?

**Comment by msoap** [comment]
Hi,

You should use single quotes for command:
```shell
shell2http -form /test 'echo $v_xx'
```
because the shell expands variables with values ​​for strings in double quotes, and in your work shell `$v_xx` is unset. 

Or another variant with double quotes: `shell2http -form /test "echo \$v_xx"`

**Comment by silverBull3t** [comment]
Still not working.

1. shell2http -form /test 'echo $v_xx'
2017/11/02 11:08:21 requires a pair of path and shell command

2. shell2http -form /test "echo \$v_xx"
Output = "\$v_xx" in the browser.

?

**Comment by msoap** [comment]
Please provide your OS and working shell.

**Comment by silverBull3t** [comment]
Windows 7
just running CMD and then running shell2http

**Comment by msoap** [comment]
`echo $x_xx` is unix-specific variant (for `sh`/`bash` like shells).

Please try:
```
shell2http -form /test "echo %v_xx%"
# or maybe:
shell2http -form /test "echo %V_XX%"
```

**Comment by silverBull3t** [comment]
Now that was a bit dump for me.
I was sure that $ was an internal usage of shell2http.
I forgot i was using DOS and that %% was the vars syntax.

anyways. thanks a lot !, works perfectly now.

**Comment by msoap** [comment]
Yes, for windows you can use all the features of `cmd` shell, and for unix all of `sh`.
I will update the documentation for the example for Windows `cmd`.
Thank you too.
