### ISSUE TITLE
Windows: Passed parameters executes differently than hardcoded parameters

### ISSUE THREAD

**Issue by NickE37** [msoap/shell2http#36]
Awesome program, but I am having a problem in Windows.  I am trying to have shell2http run a console executable that requires parameters and uses libraries (dll) in the same directory as the executable.
If I use the below to start shell2http:
`shell2http -form /Test "C:\Test\Test.exe Arg1 Arg2 Arg3"` 
and
`http://localhost:8080/Test`
It works fine.

But

If I use the below to start shell2http:
`shell2http -form /Test "C:\Test\Text.exe %v_arg1% %v_arg2% %v_arg3%"`
and
`http://localhost:8080/Test/Text.exe?arg1=Arg1&arg2=Arg2&arg3=Arg3`

then I get an error that the library dlls cannot be found (even though C:\Test is in the PATH environment variable.

Am I doing something wrong?

Thank you for your help!

**Comment by msoap** [comment]
Current working directory for server - is there where the shell2http started.
Please try: 
`shell2http -form /Test "cd C:\Test\ && Text.exe %v_arg1% %v_arg2% %v_arg3%"`

or try url: `http://localhost:8080/Test?arg1=Arg1&arg2=Arg2&arg3=Arg3`, `/Text.exe` - is not necessary.

**Comment by NickE37** [comment]
This problem persists even if I move the shell2http.exe to the C:\Test directory.

If I use the below to start shell2http:
`shell2http -form /Test "C:\Test\Test.exe Arg1 Arg2 Arg3"`
and
`http://localhost:8080/Test`
It works fine.

But

If I use the below to start shell2http:
`shell2http -form /Test "C:\Test\Text.exe %v_arg1% %v_arg2% %v_arg3%"`
and
`http://localhost:8080/Test?arg1=Arg1&arg2=Arg2&arg3=Arg3`

It still fails to find a needed dll that is in that C:\Test directory.

Any thoughts?

**Comment by msoap** [comment]
Variant: `shell2http -form /Test "cd C:\Test\ && Text.exe %v_arg1% %v_arg2% %v_arg3%"` also fails?

**Comment by NickE37** [comment]
Yes, that failed in exactly the same way.

**Comment by msoap** [comment]
I install a virtual machine with Windows and reproduced bug. The `PATH` environment variable is not passed to the script if exists `-form` option.

For temporary workaround use `-export-all-vars` option.

**Comment by msoap** [comment]
@NickE37 please use the latest version. It should fix the problem. Reopen if the problem recurs.
