### ISSUE TITLE
can't build 

### ISSUE THREAD

**Issue by andreykyz** [msoap/shell2http#42]
ubuntu@ip-172-31-4-243:~$ go build github.com/msoap/shell2http
go/src/github.com/msoap/shell2http/shell2http.go:4:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/ubuntu/go/src/context (from $GOPATH)

**Comment by msoap** [comment]
Hi, minimum supported Go version is 1.7 (where introduced `context` package).
