### ISSUE TITLE
how to upload a script then excute?

### ISSUE THREAD

**Issue by m2acgi** [msoap/shell2http#43]
How to upload a script then excute? I need some example codes. Thank u.

**Comment by msoap** [comment]
Something like that:

script `script.sh`: 
```sh
echo "hello from script"
```

shell2http:
`shell2http -form POST:/file 'cat $filepath_fname > uploaded_file.sh' /exe 'sh uploaded_file.sh'`

upload:
`curl -F fname=@script.sh 'http://localhost:8080/file'`

execute:
`curl 'http://localhost:8080/exe'`

result:
```
hello from script
```

**Comment by m2acgi** [comment]
Perfect! Thank you very much.
