### ISSUE TITLE
How to use custom custom libraries/tools/packages

### ISSUE THREAD

**Issue by cwartel** [msoap/shell2http#44]
Hi there,
Great tool you've made. I am trying to use it with a specific package say [jq](https://stedolan.github.io/jq/), or even good old curl. Both are present on my system but missing in shell2http's script contexts. I've check with PATHs but nothinhg there. It seems that everything is running contained, which is nice and secure. How could I install those packages without calling the apt-get in my script (which would be overkill) ?
Thanks fo your help

**Comment by msoap** [comment]
Hi,

if the tool is present in the OS (and in the PATH) and then it should be available for run in shell2http.

What operating system do you using? If is it Linux/macOS, for testing please run script like this:
```
shell2http /path 'echo $PATH' /jq 'type jq'
```

What is the response to the requests:
```
curl http://localhost:8080/path
curl http://localhost:8080/jq
```
?

**Comment by cwartel** [comment]
I'm using a ubuntu 16.04
launching
`
shell2http /path 'echo $PATH' /jq 'type jq' /curl 'which curl'
`


`curl http://localhost:8080/path` gives
`/snap/shell2http/14/usr/sbin:/snap/shell2http/14/usr/bin:/snap/shell2http/14/sbin:/snap/shell2http/14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games` 

`curl http://localhost:8080/jq` gives
`exec error: exit status 127`

and
`curl http://localhost:8080/curl`
`exec error: exit status 1`

I've also tried to come up with a custom Docker as per your https://github.com/msoap/shell2http#run-from-docker-container... 
Adding  `RUN apk add --no-cache jq curl` in test.Dockerfile
and calling a docker build on that, without success so far. And I'd like to know wether ther's something simpler before I go down that path

Thank you for your time and answers

**Comment by msoap** [comment]
This is snap-specific problem. Snap package has own `/usr/bin` (see https://forum.snapcraft.io/t/missing-commands-in-usr-bin/3502), where `jq` or `curl` is not present :(

as I see, there is only one solution: uninstall snap package (`sudo snap remove shell2http`) and install via [deb-package](https://github.com/msoap/shell2http/releases/latest) (`dpkg -i shell2http_1.13_amd64.deb`) or build from source (`go get -u github.com/msoap/shell2http`)

**Comment by cwartel** [comment]
HI Sergey,
Thanks a lot, that did the trick. I guess I came accross "containerization" limitation.
