### ISSUE TITLE
Cannot Set Response Header in Windows

### ISSUE THREAD

**Issue by pamubay** [msoap/shell2http#45]
in my Arch Linux environment, i have `run.sh` with content below:
```sh
#!/usr/bin/env bash
export HTML_INDEX="site/index.html"
export MAIN_JS="site/main.js"

shell2http -export-all-vars -cgi -form / "cat $HTML_INDEX" \
/echo 'echo "$v_msg"' \
/call2 'echo "Content-Type: application/json";echo ;echo "{\"error\": \"ok\"}"' \
/main.js 'echo "Content-Type: application/javascript";echo ;cat $MAIN_JS' 
```
in the script above i can set correct `Content-Type` response header of the `/main.js` path. it works correctly in browser.

now, i want to replicate script above in Windows environment (Windows 8.1) with `run.bat` below:
```batch
@echo OFF

set HTML_INDEX=site\index.html
set MAIN_JS=site\main.js
set TYPE=Content-Type: application/javascript

shell2http.exe -cgi / "type %HTML_INDEX%" ^
/main.js "echo %TYPE% & type %MAIN_JS%"
``` 
the problem is, the `Content-Type` not set in Response Header, but included in Response Body output of `/main.js`
```
Content-Type: application/javascript
alert('Hello World') <-- content inside `site\main.js`
```
i've tried adding `\n\n` and `echo.` to add newline
```
/main.js "echo %TYPE%\n\n & type %MAIN_JS%"
/main.js "echo %TYPE% & echo. & type %MAIN_JS%"
```
the `Content-Type` always included inside the Response Body.

but of course, if i only using this command below:
```
/main.js "type %MAIN_JS%"
```
the `main.js` script executed by the browser successfully, but with `Content-Type: text/plain`.

How to make the Response Header setting works in windows?

**Comment by msoap** [comment]
Why not used `-export-all-vars` option in `run.bat` like in `run.sh`?

Or please try (twice `echo.`):
`/main.js "echo %TYPE% & echo. & echo. & type %MAIN_JS%"`

**Comment by pamubay** [comment]
i don't use `-export-all-vars` flag because all the variables inside the `run.bat` already works as expected.

here i test the code with `-export-all-vars` flags with double `echo.`  : 
```
shell2http.exe -export-all-vars -cgi / "type %HTML_INDEX%" ^
/main.js "echo %TYPE% & echo. & echo. & type %MAIN_JS%"
```
the `echo.` corectly add newline. Here the screenshot from Google Chrome (68.0.3440.84) response body:

![body-response](https://user-images.githubusercontent.com/18132440/44629368-84900200-a978-11e8-979d-52aabced939d.PNG)

i wonder if it's related with the line ending the OS used as the unix `\n` and windows `\r\n`.
i've already tried to save the `run.bat` with `\n`  using Notepad2-mod, but stil not working.

**Comment by msoap** [comment]
As a workaround please try adding a header inside to `main.js`, with two `\n` after header.
And run: `/main.js "type %MAIN_JS%"`

And I'll try to debug on windows.

**Comment by pamubay** [comment]
Thanks, it works!

But, why this code doesnt work? the code below is manually typed.
```
Content-Type: application/javascript\n\nalert('Hello World')
```

it's working if i set the `Line Ending` to `UNIX (LF)` in my Notepad2, then adding `\n` by pressing Enter.
 
![line-ending](https://user-images.githubusercontent.com/18132440/44629714-61b41c80-a97d-11e8-82bf-86cad42858fa.PNG)

But, Yeah the workaround is enough to solve my problem. Thanks. :+1:

**Comment by msoap** [comment]
Hi, I investigated the problem on windows. The reason is space between two new lines after headers:
```
/main.js "echo %TYPE% & echo. & echo. & type %MAIN_JS%"
```

This variant should work correctly:
```
```
