### ISSUE TITLE
How to start shell2http?

### ISSUE THREAD

**Issue by zervankoru** [msoap/shell2http#46]
Currently my bash script is
#!/bin/bash
PWD=/root
SHELL=/bin/bash
PATH=some path variables
cd $PWD
shell2http -port=80 -export-all-vars and my commands

Well. I actually dont understand how shell2http work with enviroment vars. What does -export-all-vars do?

**Comment by msoap** [comment]
`-export-all-vars` - this option makes available all environment variables that are visible to the shell2http.

For debugging you can use this command:
`shell2http -export-all-vars /env 'printenv | sort'`
and:
`curl http://localhost:8080/env`

btw, for use your own variable in script, you should define it with export:
`export PATH=...`

**Comment by msoap** [comment]
May be useful option `-show-errors`.

`shell2http -show-errors /test 'sh -c "echo ok; exit 255"'`

`curl http://localhost:8080/test`

result:
`ok`

**Comment by zervankoru** [comment]
Thanks!
