### ISSUE TITLE
Passing flags to docker container

### ISSUE THREAD

**Issue by borisfeldman** [msoap/shell2http#47]
Great tool. I'm relatively new to docker and am having trouble passing flags to a container I've built from your image that's running on Ubuntu.

Here is my Dockerfile:
`FROM msoap/shell2http`
`CMD ["-form /date 'date'"]`

After building, I run the container with this command:
`
docker run --rm -p 7777:8080 test-server
`

I get this error:
`
flag provided but not defined: -form /date 'date'
`

Am I missing something super simple? Without the "-from" everything works. Thanks!

**Comment by borisfeldman** [comment]
Argh! Never mind I found my (own) error:
`CMD ["-form","/date","date"]`

**Comment by dachev** [comment]
This got me too!
