### ISSUE TITLE
Install on Raspberry pi

### ISSUE THREAD

**Issue by amilino** [msoap/shell2http#48]
Hi,

how to install this on Raspberry Pi?

Thank you in advance.

Regards,
amilino

**Comment by amilino** [comment]
Ok, I just had to extract all to /usr/local/bin.

**Comment by jantielens** [comment]
Hi, I was searching to do the same, but I can't get it to work on my Raspberry Pi. Can you explain what you did? Which files did you extract to /usr/local/bin ? Thanks!

**Comment by msoap** [comment]
@jantielens you can try:
```
curl -Ls https://github.com/msoap/shell2http/releases/download/1.13/shell2http-1.13.linux.arm.tar.gz | tar -C /usr/local/bin shell2http -xzf -
```
