### ISSUE TITLE
Arguments not working

### ISSUE THREAD

**Issue by amilino** [msoap/shell2http#49]
If I have a shell like this "shell_script --help", and started the server like this:
`shell2http /testing 'shell_script $v_arg1'`

It doesn't work if I run it in my browser like this:
`http://localhost:8080/testing?arg1=--help`

How to send arguments of the shell script correctly?

**Comment by msoap** [comment]
You should use the `-form` option:
```
shell2http -form /testing 'echo $v_arg1'
```

**Comment by amilino** [comment]
Hi, thank you it is working. However, I started to build a php script to execute shell scripts.
