### ISSUE TITLE
HTTP status code

### ISSUE THREAD

**Issue by yamamoto-hiroki** [msoap/shell2http#51]
Thank you for this great tool, we use it as health check endpoints for a variety of services. Is it possible to change the HTTP status code from '200' to let's say '500' when executed script returns a exit code other then '0' ? This would allow a health check status to be validated based solely on HTTP status code rather than string output. This would cover certain health check validators that lack string output validation.

**Comment by msoap** [comment]
Hi,

you can use custom http-codes from shell script in `-cgi` mode:

```
shell2http -show-errors -cgi /health './error.sh > /dev/null || echo "Status: 503\n\nError\n"' /ok './ok.sh || echo "Status: 503\n\nError\n"'

```

`error.sh` - this script ends with non-zero code:
```
#!/bin/sh

echo Error
exit 1
```

`ok.sh` - with 0 code:
```
#!/bin/sh

echo Ok
```

result:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/844117/65914531-38648c00-e3da-11e9-8c04-7445f0e9403c.png">

**Comment by msoap** [comment]
@yamamoto-hiroki did you solve your problem?
