### ISSUE TITLE
Unable to query mysql

### ISSUE THREAD

**Issue by shashank-google** [msoap/shell2http#53]
Hi,
I am trying to create mysql heartbeat on http using this tool.
So I want to execute something as below:

`shell2http /showStatus '/var/lib/snapd/snap/bin/mysql.client --user=root --password=root -h 127.0.0.1 -e "select 1+1"'`

I installed `sudo snap install --beta mysql` as well but couldn't figure out.
Can you please help. 
Note: actual database in on same instance.

**Comment by msoap** [comment]
Hi,
how did you install the `shell2http`? also via `snap`? If yes - this may be the reason, and please try reinstall via deb-package or just run binary from [releases](https://github.com/msoap/shell2http/releases)

**Comment by msoap** [comment]
I tried run same script:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/844117/68980910-81499600-080a-11ea-93e7-498509bde7dc.png">

but used `mysql-client` installed from `homebrew` and `shell2http` installed from binaries

**Comment by shashank-google** [comment]
Yes, I am using snap to install it.
I am using it on centos. Can you give me exact installation steps for
redhat package manager.

**Comment by msoap** [comment]
Unfortunately there is currently no rpm-package.

You can try something like this:
```
curl -Ls https://github.com/msoap/shell2http/releases/download/1.13/shell2http-1.13.linux.amd64.tar.gz | sudo tar -C /usr/local/bin/ -xzf - shell2http
```

And before, please uninstall shell2http snap package.

**Comment by msoap** [comment]
@shashank-google did this install method help you?

**Comment by shashank-google** [comment]
Hi Sergey,

I am yet to try it. I moved on to write custom python code. But anyways, I
will give it a try once I get time.

**Comment by shashank-google** [comment]
Thanks Sergey. 
Your command to untar and copy utility (below) works.
I am able to execute mysql command (or any other) on centos.

```
curl -Ls https://github.com/msoap/shell2http/releases/download/1.13/shell2http-1.13.linux.amd64.tar.gz | sudo tar -C /usr/local/bin/ -xzf - shell2http
```

**Comment by msoap** [comment]
ok,
`snap` packages have a lot restrictions because the binaries are in their own "sendboxes".
