### ISSUE TITLE
exec error: exit status 1 

### ISSUE THREAD

**Issue by selvakumar7991** [msoap/shell2http#56]
C:\Selva\software\shell2http>shell2http -form /starttest  "C:\Selva\software\shell2http\script.bat"
2020/03/02 14:17:56 register: /starttest (C:\Selva\software\shell2http\script.bat)
2020/03/02 14:17:56 register: / (index page)
2020/03/02 14:17:56 listen http://:8080/
2020/03/02 14:18:05 localhost:8080 [::1]:55677 GET /starttest "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
2020/03/02 14:18:05 exec error:  exit status 1

Getting above error when we tired  an api for executing a bat file
http://localhost:8080/starttest

**Comment by msoap** [comment]
The reason is that the script (`script.bat`) exits with code 1.
You can try use `-show-errors` options for show this error in browser.

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75666012-16c64400-5c9b-11ea-95f6-3ef2882d15d6.png)
My browser showing empty response after adding -show-errors option for show this error in browser like below

shell2http -form -show-errors /starttest  "C:\Selva\software\shell2http\script.bat"
2020/03/02 15:32:07 register: /starttest (C:\Selva\software\shell2http\script.bat)
2020/03/02 15:32:07 register: / (index page)
2020/03/02 15:32:07 listen http://:8080/
2020/03/02 15:32:09 localhost:8080 [::1]:57083 GET /starttest "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
2020/03/02 15:32:09 exec error:  exit status 1

**Comment by msoap** [comment]
sorry, it turned out that this option is about another. Anyway, you should investigate your script, why it exits with code 1

**Comment by selvakumar7991** [comment]
okay thanks man

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75668019-a4eff980-5c9e-11ea-9355-c2c002aeeed9.png)

I tired with basic command in the bat file, Still getting above error only, Do you any idea about this

**Comment by selvakumar7991** [comment]
shell2http -form /starttest  "C:\Selva\software\shell2http\sam.bat"
2020/03/02 15:56:06 register: /starttest (C:\Selva\software\shell2http\sam.bat)
2020/03/02 15:56:06 register: / (index page)
2020/03/02 15:56:06 listen http://:8080/
2020/03/02 15:56:09 localhost:8080 [::1]:58464 GET /starttest "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
2020/03/02 15:56:09 exec error:  exit status 1
2020/03/02 15:56:11 localhost:8080 [::1]:58464 GET /starttest "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
2020/03/02 15:56:11 exec error:  exit status 1

**Comment by msoap** [comment]
I don’t have Windows right now, but please try that script:

```shell
ipconfig

if errorlevel 1 (
   echo Failure reason given is %errorlevel%
   exit /b 0
)

```

and run command like this:
```
shell2http -include-stderr /starttest "c:\path\to\script\sam.bat"
```

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75670395-a7545280-5ca2-11ea-8adb-8a3b5251aa53.png)


still getting same issue. let me try this same in linux machine

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75670556-f7331980-5ca2-11ea-86bb-df972847d5cd.png)

**Comment by msoap** [comment]
You should use real path to script, not `"c:\path\to\script\sam.bat"` (this is example)

**Comment by msoap** [comment]
And please just run this script from terminal, is it running normally?

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75678087-d246a280-5cb2-11ea-8a07-f4ce36df3387.png)
ran this script from terminal, it is running fine

**Comment by selvakumar7991** [comment]
![image](https://user-images.githubusercontent.com/18574716/75678572-f48cf000-5cb3-11ea-8b9c-0678ca6d401c.png)
folder structure for your reference

**Comment by msoap** [comment]
i see - test.bat is nothing output

**Comment by msoap** [comment]
you can use ipconfig directly:
```
shell2http -include-stderr /starttest ipconfig
```

**Comment by selvakumar7991** [comment]
tired to use directly, but getting different error


shell2http.exe -include-stderr -port=8010 /test "C:\Selva\NeoLoad 7.2\bin\\NeoLoadCmd.exe"
2020/03/03 12:27:41 register: /test (C:\Selva\NeoLoad 7.2\bin\\NeoLoadCmd.exe)
2020/03/03 12:27:41 register: / (index page)
2020/03/03 12:27:41 listen http://:8010/
2020/03/03 12:27:49 localhost:8010 [::1]:58124 GET /test "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
2020/03/03 12:27:59 exec error:  exit status 3221226505

**Comment by msoap** [comment]
script (or any program) must be return `0` exit code, in any other case there will be such an error

**Comment by selvakumar7991** [comment]
Planning to build an own API according to my recruitment, Anyway, Thanks for your help
