### ISSUE TITLE
Inconsistent permissions on shell command

### ISSUE THREAD

**Issue by flaviotsales** [msoap/shell2http#57]
When running the program like so
```bash
shell2http -port=80 / "tail /root/server/logs/logfile.log"
```

it gives the following output when a request is received
```bash
tail: cannot open '/root/server/logs/logfile.log' for reading: Permission denied
2020/04/01 13:09:57 exec error:  exit status 1
```

but the command
```bash
tail /root/server/logs/logfile.log
```
can be executed normally outside shell2http.

OS Ubuntu 18.04
The program is being executed by the root user.
The file and directories and are owned by user and group root.
The permissions are as follows:
root: 700
server: 775
logs: 644
logfile.log: 644

I've managed to make shell2http execute the command by setting permissions 744 on the "logs" folder but I'm confused for the reason that it's working.
From what I understood while searching for the answer, directories must have the "x" permission to allow acessing it's files ([StackExchange/AskUbuntu](https://askubuntu.com/questions/83788/accessing-files-in-a-directory-without-x-permission)), so theoretically my shell is wrong for letting me access the contents of the logs folder, unless there is something special about the root user.

Shouldn't the 2 situations execute the command in the same way?

It may be that this question is more Ubuntu/Linux than about shell2http, so please let me know if here is the appropriate place for it.

**Comment by msoap** [comment]
You definitely run both commands (`shell2http` and `tail`) under the same user?
`tail` and `tail` under `shell2http` should work the same, i checked it now.

Maybe try copying the log-file to the current directory and run `tail logfile.log`, what will be happened?

**Comment by flaviotsales** [comment]
Yes, both command were executed by the root user.

Copying the file to the current directory and running `tail logfile.log` is working with or without the "x" permission in the parent folders.

The `tail` command inside `shell2http -port=80 / "tail /many/folders/logfile.log"` is working only if all parent folders of `logfile.log` have the "x" permission, regardless of the logfile being moved up or down some directories.

**Comment by msoap** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/844117/78279286-f8fd3080-751f-11ea-96aa-9b30142c5df2.png">

not reproducing, `tail` has the same behavior under `shell2http` and without

**Comment by flaviotsales** [comment]
Something very weird is going on...

shell2http is the snap version

shell2http/shell2http is compiled from source (`git clone` and `go build`)
Same result with `go get`

![image](https://user-images.githubusercontent.com/18455124/78294241-64370a80-7500-11ea-8b3f-c8e54e958ead.png)

**Comment by msoap** [comment]
Oh, yes, applications from snap packages have their own sandbox which provides many limitations, for example restrict access to host filesystem.

**Comment by msoap** [comment]
Nothing can be done here, with snap shell2http. Please use deb-package or binary from github releases or build from source.

**Comment by flaviotsales** [comment]
I would never thought of that. Now that I know what the issue is, I'm starting to find some problems related to that while searching.
Compiling the program myself definitely solves the issue for me.

Thanks for your help, greatly appreciated.

**Comment by msoap** [comment]
You're welcome

**Comment by flaviotsales** [comment]
For posterity, here are the details of the snap isolation rules:

https://snapcraft.io/docs/snap-confinement
https://snapcraft.io/docs/permission-requests

Installing from snap with `--devmode` option also solves the permission issue by giving the program full access to systems resources.
