### ISSUE TITLE
docker: not found

### ISSUE THREAD

**Issue by filanovskiy** [msoap/shell2http#61]
when I'm calling bash scripts, which contains docker command I get an exception:
`docker: not found`
Note: I've installed shell2https with snap, like:
`sudo snap install shell2http`

**Comment by msoap** [comment]
snap packages have many restrictions, see notice: _the snap-package has its own sandbox with the /bin, /usr/bin directories which are not equal to system-wide PATH directories._
Please use deb-package or binary from [releases](https://github.com/msoap/shell2http/releases/latest)

**Comment by filanovskiy** [comment]
thank you this worked!
