### ISSUE TITLE
Am I supposed to see some sort of output from - shell2http /top "top -l 1 | head -10"

### ISSUE THREAD

**Issue by bmullan** [msoap/shell2http#62]
I installed the SNAP on my Ubuntu 20.04

I executed several of the "Examples" for instance:

> $ **shell2http /top "top -l 1 | head -10"**
> 2020/09/11 11:33:32 register: /top (top -l 1 | head -10)
> 2020/09/11 11:33:32 register: / (index page)
> 2020/09/11 11:33:32 listen http://localhost:8080/

Am I supposed to see something more than the above?   Maybe I am misunderstanding the use of this tool?

Thanks for any enlightenment.

Brian

**Comment by msoap** [comment]
Hi Brian,
you see server logs, that's all there is. Because this is an http server, then you can see the shell command output in the browser.
