### ISSUE TITLE
Is it possible to start a systemctl command ?

### ISSUE THREAD

**Issue by johnchristopher** [msoap/shell2http#65]
Hello,

I get a `Failed to connect to bus: No such file or directory` when trying to run a `systemctl` command to grab the status of a service:

```shell
$ ./shell2http /test 'systemctl is-active --user --quiet myservice && echo "myservice is active"'
```

shell2http output:
```
Failed to connect to bus: No such file or directory
2020/11/21 11:51:49 exec error:  exit status 1
```

I tried launching shell2http as root and using `su` in the command but it still fails in the same way.

Is it possible to send back systemctl output ?

**Comment by srd424** [comment]
At a guess, `--export-vars=DBUS_SESSION_BUS_ADDRESS` might do it?

**Comment by johnchristopher** [comment]
Thanks, that did it :).

Apart from writing simple service units my knowledge of DBUS is rather limited.

**Comment by msoap** [comment]
@srd424 thanks!
