### ISSUE TITLE
Crashes on launch on Apple Silicon

### ISSUE THREAD

**Issue by chetstone** [msoap/shell2http#66]
When I got my shiny new MacMini with the M1 chip, migration assistant transferred my entire homebrew installation from my Intel mac. Somewhat surprisingly, it almost all "just worked" under Rosetta. The only exception I have found so far is `shell2http`. 

Workaround: Build a native M1 version of `go` according to the [instructions here.](https://github.com/golang/go/issues/38485#issuecomment-730247329)
Then in this directory, do:

```sh
make build
codesign -s - ./shell2http
```

Voila!

**Comment by msoap** [comment]
Thanks for the advice, but all binaries are builded on CI (TravisCI) under Linux. I'll investigate how to sign under linux (and build for M1).
Perhaps a signature is required for Big Sur and for intel too, can someone check it?

**Comment by chetstone** [comment]
I'm pretty sure codesigning is not required for intel. After all, I was able to run almost my entire homebrew suite after copying it over from an intel machine with no extra signing or modification needed. Including large apps like emacs and postgresql, they all work with more than adequate performance under Rosetta.

The problem is something to do with `go` running under Rosetta. Perhaps [this issue](https://github.com/golang/go/issues/42700) is relevant.

**Comment by msoap** [comment]
@chetstone could you please to check the latest release - https://github.com/msoap/shell2http/releases/tag/v1.14.1 
I've migrated to the Github Actions and `goreleaser` for build and now distribution for Apple Silicon placed in `shell2http_1.14.1_darwin_arm64.tar.gz` file

**Comment by chetstone** [comment]
Sorry about the delay.. I had moved my use of shell2http to another machine, but I just installed 1.14.1 via homebrew on my M1 machine and it works fine.Thanks!via Newton MailOn Sat, Nov 13, 2021 at 8:53, Sergey Mudrik ***@***.***> wrote:
Closed #66.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/msoap/shell2http/issues/66#event-5613278360",
"url": "https://github.com/msoap/shell2http/issues/66#event-5613278360",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by msoap** [comment]
@chetstone thanks for feedback.
