### ISSUE TITLE
An option to make the server handle only one request? I.e. shutdown after giving the response.

### ISSUE THREAD

**Issue by Nakilon** [msoap/shell2http#73]
I want it for my Google Cloud Run thing to be sure it'll not reuse the instance.

**Comment by msoap** [comment]
@Nakilon shell2http already have `-add-exit` option, which add `/exit` route to the server. And you can call your main route and then `http://servername/exit`

**Comment by Nakilon** [comment]
But there is time between two external calls...

**Comment by msoap** [comment]
For minimize time, you can call /exit from main route, like this:
```
shell2http -add-exit /main 'main_script.sh; curl http://server/exit'
```

**Comment by Nakilon** [comment]
Currently I solved it by putting `rm script.sh` as the first line of `rm script.sh`.
