### ISSUE TITLE
Serve file from disk

### ISSUE THREAD

**Issue by gmile** [msoap/shell2http#74]
Is there a way / example of how to serve a static file?

My use-case:
* upon request, generate a bunch of files on the disk,
* upon sub-sequent request containing a file name, find that file on disk and generate response.

**Comment by msoap** [comment]
Something like that:
```
shell2http -form /index 'find . -type f | xargs -I@ echo "<a href=/get?file=@>@</a><br>"' /get 'cat $v_file'
```

**Comment by gmile** [comment]
@msoap works, thank you!
