### ISSUE TITLE
"No such file or directory" err

### ISSUE THREAD

**Issue by SirYaro** [msoap/shell2http#78]
Hi Serhii
Would you advise me, what am I doing wrong ?

```
yaro@yaro-desktop2:~$ /usr/bin/amarok --play-pause
yaro@yaro-desktop2:~$ which /usr/bin/amarok
/usr/bin/amarok
yaro@yaro-desktop2:~$ shell2http -shell="bash" -export-all-vars /amarok '/usr/bin/amarok --play-pause'
2022/04/02 16:33:08 register: /amarok (/usr/bin/amarok --play-pause)
2022/04/02 16:33:08 register: / (index page)
2022/04/02 16:33:08 listen http://localhost:8080/
bash: /usr/bin/amarok: No such file or directory
2022/04/02 16:33:13 exec error:  exit status 127
2022/04/02 16:33:13 localhost:8080 127.0.0.1:52452 "GET /amarok" 200 27 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0" 2ms
^C
yaro@yaro-desktop2:~$
```

When I used shell2http to display files from /usr/bin/ I got a totally different set of files than I really have. Is that that tool closed in some kind of container or sth? If so, is there a way to bypass this?

**Comment by SirYaro** [comment]
Crisis solved. :)
I check shell2http-1.7.linux.amd64.zip, and it's working just fine.
Looks like problem related only to snap version

**Comment by msoap** [comment]
Yes, snap-version have own sandbox environment with own fs
