### ISSUE TITLE
How can get request body from command? (question） 

### ISSUE THREAD

**Issue by eggcaker** [msoap/shell2http#79]
Like， from client i send a POST request with some json body, How can I get that body content from script ?

**Comment by msoap** [comment]
Hi @eggcaker 
you can use `-cgi` option for that, and POST data will get on stdin, something like:

```
shell2http -cgi /jq 'jq'
```

and

```
$ curl -X POST -d '{"id":123}' http://localhost:8080/jq
{
  "id": 123
}
```

**Comment by eggcaker** [comment]
thanks！
