### ISSUE TITLE
What are these logs? 

### ISSUE THREAD

**Issue by opcache** [msoap/shell2http#85]
What are these logs? Can these logs be turned off?
2022/10/10 09:45:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/ccd/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:46:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/certs/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:46:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/ccd/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:47:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/certs/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:47:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/ccd/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:48:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/certs/download?token=true" 401 26 "Go-http-client/1.1" 0s
2022/10/10 09:48:11 127.0.0.1:8080 127.0.0.1:50068 "GET /api/data/ccd/download?token=true" 401 26 "Go-http-client/1.1" 0s

**Comment by msoap** [comment]
you can use `-log` option:
```
shell2http -log /dev/null ...
```
