### ISSUE TITLE
Ability to define multiple endpoints in dockerfile

### ISSUE THREAD

**Issue by Semetra22** [msoap/shell2http#89]
I would like to define multiple endpoints in the Dockerfile. 

Here is my Dockerfile:
```
FROM msoap/shell2http
RUN apk add --no-cache curl

EXPOSE 8080
CMD ["-no-index","-form","-log=endpoint1.log","/v0/endpoint1","/scripts/script1.sh $v_param"]
CMD ["-no-index","-log=endpoint2.log","/v0/endpoint2","/scripts/script2.sh $v_param"]
```

However, only the last command is executed after the build. 
Any idea?

**Comment by msoap** [comment]
Docker not supported several CMD's, but you can run two endpoints on one shell2http
