### ISSUE TITLE
 Support configuration file method

### ISSUE THREAD

**Issue by opcache** [msoap/shell2http#90]
There are many commands and interfaces that need to be opened. Is it possible to support the configuration file method?

**Comment by msoap** [comment]
Do you mean GET/POST method for endpoints?

**Comment by opcache** [comment]
> Do you mean GET/POST method for endpoints?
> 
> You can configure it like:
> 
> ```
> shell2http GET:/date date
> ```

Yes, many interfaces and commands

**Comment by msoap** [comment]
@opcache separated config file not possible, but you can create shell script like:
```shell
$ cat server.sh
#!/bin/sh
shell2http \
  /date date \
  /ps "ps aux" \
  /df  "df -h" \
  /w  w \
  /free  free
```

**Comment by msoap** [comment]
or create config and use it in commandline:

```
$ cat config.cfg
/date date 
/ps "ps aux"
/df  "df -h"
/w  w
/free  free
```

and then use it
```
shell2http $(cat config.cfg)
```

**Comment by opcache** [comment]
Ok,thank you very much
