### ISSUE TITLE
Documentation for docker should include details about using --init

### ISSUE THREAD

**Issue by kratsg** [msoap/shell2http#96]
See this (old) blog post: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ and this solution (https://github.com/krallin/tini) which is now built into docker via `--init`. The shell scripts run by `shell2http` will typically become zombie and won't be cleaned up without `--init` or an init-script in the docker image.

**Comment by msoap** [comment]
Hi @kratsg, sorry for dalay, I don't see this problem in my docker containers even if they have been running for months and are heavily used.
Could you please provide minimal example like Dockerfile with build/run command and with such issue (and without --init)?

**Comment by kratsg** [comment]
Hi @msoap that's fine -- see this [repo](https://github.com/kratsg/dockerimages/tree/master/eos-krb5-shell2http) which contains the `Dockerfile`. Nothing very complicated, but we've observed zombie processes not getting cleaned up over time. The solution is to run the docker image with `--init` which you can't specify as part of the `Dockerfile` unless you include `tini` manually.
