### ISSUE TITLE
Streaming endpoints

### ISSUE THREAD

**Issue by goncalo-oliveira** [msoap/shell2http#97]
Hi,

Is there any way to achieve a streaming endpoint?

Picture the following scenario

```bash
CMD shell2http -cgi \
    -export-vars="irrelevant" \
    POST:/ '/app/function.sh && printf "%s\n\n%s\n" "Status: 202" "Accepted"' \
    GET:/logs "tail -f /var/log/function.log"
```

The `POST` essentially starts a long-running process in the background, hence me returning a 202. However, because I am returning immediately, I still want a way to access the logs of the process if I want.
The `tail` is usually a good way of doing that (locally). But with the above script, this doesn't work as I expected, since it actually blocks the request and it only returns when it ends (which is what we are asking for).

Is there any way that this could be achieved?

**Comment by msoap** [comment]
Hi, currently no, but maybe in future,
already have issue like this: #33

**Comment by goncalo-oliveira** [comment]
Thanks for the quick reply @msoap. Didn't see that issue. This can be closed as a duplicate then...
