### ISSUE TITLE
logging to file does not include stderr from shell commands

### ISSUE THREAD

**Issue by freol35241** [msoap/shell2http#99]
Using the option to output logs to file (`-log=filename`) I would expect to see both the stdout/stderr of the shell2http process and stderr from any invoked subcommand to show up there. Currently, tough, it seems like only stdout/stderr from the shell2http process gets piped to the log file.

**Comment by dubiouscript** [comment]
... i searched for tty and dint see this mentioned any where ( that said i search git~hub for shell2http and got zero results =s )
 
iv just found using 

>cat - | tee ./svr-log000.txt >/dev/tty ; 

will print the post data to the terminal where shell2httpd was run from 
i added   -log=s2h-log.txt
but >/dev/tty  add any more out put to the log ftr

eg
`
shell2http -log=s2h-log.txt -cgi / 'echo "Access-Control-Allow-Origin: *\n" ;echo foo  ; cat - | tee ./svr-log000.txt >/dev/tty ; '`

:sunglasses:

**Comment by msoap** [comment]
Hi @freol35241, it should be fixed with the latest commit, could you please test?
